In [3]:
!pip install kaggle

Collecting kaggle
  Downloading https://files.pythonhosted.org/packages/80/4d/fc83980735a7a2e3aaba1ed755462e839c68ba51ac311efdb1ab413a4eeb/kaggle-1.5.2.tar.gz (54kB)
Collecting urllib3<1.23.0,>=1.15 (from kaggle)
  Downloading https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl (132kB)
Requirement already satisfied: six>=1.10 in c:\users\valerie\anaconda3\lib\site-packages (from kaggle) (1.11.0)
Requirement already satisfied: certifi in c:\users\valerie\anaconda3\lib\site-packages (from kaggle) (2018.11.29)
Requirement already satisfied: python-dateutil in c:\users\valerie\anaconda3\lib\site-packages (from kaggle) (2.7.3)
Requirement already satisfied: requests in c:\users\valerie\anaconda3\lib\site-packages (from kaggle) (2.19.1)
Requirement already satisfied: tqdm in c:\users\valerie\anaconda3\lib\site-packages (from kaggle) (4.26.0)
Collecting python-slugify (from kaggle)
  Downloading https://files.pythonhosted.org/packages/1f/9c/8b07d625e9c9df567986d887f0375075abb1923e49d074a7803cd1527dae/python-slugify-2.0.1.tar.gz
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\valerie\anaconda3\lib\site-packages (from requests->kaggle) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in c:\users\valerie\anaconda3\lib\site-packages (from requests->kaggle) (2.7)
Collecting Unidecode>=0.04.16 (from python-slugify->kaggle)
  Downloading https://files.pythonhosted.org/packages/31/39/53096f9217b057cb049fe872b7fc7ce799a1a89b76cf917d9639e7a558b5/Unidecode-1.0.23-py2.py3-none-any.whl (237kB)
Building wheels for collected packages: kaggle, python-slugify
  Running setup.py bdist_wheel for kaggle: started
  Running setup.py bdist_wheel for kaggle: finished with status 'done'
  Stored in directory: C:\Users\Valerie\AppData\Local\pip\Cache\wheels\0d\58\eb\83d6a2e1935aff39d341ffa1e5faa3809e173cd0937e057d83
  Running setup.py bdist_wheel for python-slugify: started
  Running setup.py bdist_wheel for python-slugify: finished with status 'done'
  Stored in directory: C:\Users\Valerie\AppData\Local\pip\Cache\wheels\2b\9e\c8\14a18ab55d8f144384de8186a3df8401dcc9264936f71d470f
Successfully built kaggle python-slugify
Installing collected packages: urllib3, Unidecode, python-slugify, kaggle
  Found existing installation: urllib3 1.23
    Uninstalling urllib3-1.23:
      Successfully uninstalled urllib3-1.23
Successfully installed Unidecode-1.0.23 kaggle-1.5.2 python-slugify-2.0.1 urllib3-1.22

twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
spyder 3.3.2 requires pyqt5<5.10; python_version >= "3", which is not installed.
You are using pip version 10.0.1, however version 19.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [5]:
!python -m pip install --upgrade pip

Collecting pip
  Downloading https://files.pythonhosted.org/packages/46/dc/7fd5df840efb3e56c8b4f768793a237ec4ee59891959d6a215d63f727023/pip-19.0.1-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-19.0.1

twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
spyder 3.3.2 requires pyqt5<5.10; python_version >= "3", which is not installed.

In [7]:
!kaggle competitions download -c ds1-predictive-modeling-challenge

Downloading sample_submission.csv to C:\Users\Valerie

Downloading test_features.csv.zip to C:\Users\Valerie

Downloading train_labels.csv.zip to C:\Users\Valerie

Downloading train_features.csv.zip to C:\Users\Valerie

  0%|          | 0.00/236k [00:00<?, ?B/s]
100%|##########| 236k/236k [00:00<00:00, 2.41MB/s]

  0%|          | 0.00/948k [00:00<?, ?B/s]
100%|##########| 948k/948k [00:00<00:00, 5.26MB/s]

  0%|          | 0.00/211k [00:00<?, ?B/s]
100%|##########| 211k/211k [00:00<00:00, 5.71MB/s]

  0%|          | 0.00/3.81M [00:00<?, ?B/s]
 26%|##6       | 1.00M/3.81M [00:00<00:00, 4.24MB/s]
 53%|#####2    | 2.00M/3.81M [00:00<00:00, 4.21MB/s]
 79%|#######8  | 3.00M/3.81M [00:00<00:00, 3.89MB/s]
100%|##########| 3.81M/3.81M [00:01<00:00, 3.82MB/s]

In [8]:
import pandas as pd
pd.set_option('max_columns', 100)
train = pd.read_csv('train_features.csv.zip')
test = pd.read_csv('test_features.csv.zip')  # Unlabeled, for Kaggle submission
labels = pd.read_csv('train_labels.csv.zip')
train = train.join(labels.status_group, how='inner')
train.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,status_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,Roman,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,280,NaN,GeoData Consultants Ltd,Other,NaN,True,2010,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,functional
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,Nyumba ya mungu pipe scheme,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe,functional
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,NaN,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,non functional
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,0,True,GeoData Consultants Ltd,NaN,NaN,True,0,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,functional

In [9]:
train.describe()

,id,amount_tsh,gps_height,longitude,latitude,num_private,region_code,district_code,population,construction_year
count,59400.000000,59400.000000,59400.000000,59400.000000,5.940000e+04,59400.000000,59400.000000,59400.000000,59400.000000,59400.000000
mean,37115.131768,317.650385,668.297239,34.077427,-5.706033e+00,0.474141,15.297003,5.629747,179.909983,1300.652475
std,21453.128371,2997.574558,693.116350,6.567432,2.946019e+00,12.236230,17.587406,9.633649,471.482176,951.620547
min,0.000000,0.000000,-90.000000,0.000000,-1.164944e+01,0.000000,1.000000,0.000000,0.000000,0.000000
25%,18519.750000,0.000000,0.000000,33.090347,-8.540621e+00,0.000000,5.000000,2.000000,0.000000,0.000000
50%,37061.500000,0.000000,369.000000,34.908743,-5.021597e+00,0.000000,12.000000,3.000000,25.000000,1986.000000
75%,55656.500000,20.000000,1319.250000,37.178387,-3.326156e+00,0.000000,17.000000,5.000000,215.000000,2004.000000
max,74247.000000,350000.000000,2770.000000,40.345193,-2.000000e-08,1776.000000,99.000000,80.000000,30500.000000,2013.000000

In [10]:
train.status_group.value_counts()

functional                 32259
non functional             22824
functional needs repair     4317
Name: status_group, dtype: int64

In [11]:
id = train.id
id.head()

0    69572
1     8776
2    34310
3    67743
4    19728
Name: id, dtype: int64

In [12]:
train = train.drop('id', axis=1)
train.head()

,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,status_group
0,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,Roman,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
1,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,280,NaN,GeoData Consultants Ltd,Other,NaN,True,2010,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,functional
2,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,Nyumba ya mungu pipe scheme,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe,functional
3,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,NaN,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,non functional
4,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,0,True,GeoData Consultants Ltd,NaN,NaN,True,0,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,functional

In [13]:
train.dtypes

amount_tsh               float64
date_recorded             object
funder                    object
gps_height                 int64
installer                 object
longitude                float64
latitude                 float64
wpt_name                  object
num_private                int64
basin                     object
subvillage                object
region                    object
region_code                int64
district_code              int64
lga                       object
ward                      object
population                 int64
public_meeting            object
recorded_by               object
scheme_management         object
scheme_name               object
permit                    object
construction_year          int64
extraction_type           object
extraction_type_group     object
extraction_type_class     object
management                object
management_group          object
payment                   object
payment_type              object
water_quality             object
quality_group             object
quantity                  object
quantity_group            object
source                    object
source_type               object
source_class              object
waterpoint_type           object
waterpoint_type_group     object
status_group              object
dtype: object

In [14]:
train.date_recorded = pd.to_datetime(train.date_recorded)
train.dtypes

amount_tsh                      float64
date_recorded            datetime64[ns]
funder                           object
gps_height                        int64
installer                        object
longitude                       float64
latitude                        float64
wpt_name                         object
num_private                       int64
basin                            object
subvillage                       object
region                           object
region_code                       int64
district_code                     int64
lga                              object
ward                             object
population                        int64
public_meeting                   object
recorded_by                      object
scheme_management                object
scheme_name                      object
permit                           object
construction_year                 int64
extraction_type                  object
extraction_type_group            object
extraction_type_class            object
management                       object
management_group                 object
payment                          object
payment_type                     object
water_quality                    object
quality_group                    object
quantity                         object
quantity_group                   object
source                           object
source_type                      object
source_class                     object
waterpoint_type                  object
waterpoint_type_group            object
status_group                     object
dtype: object

In [15]:
from sklearn.model_selection import train_test_split
train_num = train.select_dtypes('number')
X = train_num
y = train.status_group
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((44550, 9), (14850, 9), (44550,), (14850,))

In [17]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression().fit(X_train, y_train)
log_reg.score(X, y)

0.5577609427609428

In [35]:
from sklearn.metrics import accuracy_score, classification_report
y_pred = log_reg.predict(X_test)
print(classification_report(y_test, y_pred))
print('accuracy', accuracy_score(y_test, y_pred))

                         precision    recall  f1-score   support

             functional       0.56      0.97      0.71      8098
functional needs repair       0.00      0.00      0.00      1074
         non functional       0.61      0.09      0.15      5678

            avg / total       0.54      0.56      0.44     14850

accuracy 0.5608080808080808

C:\Users\Valerie\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [36]:
y_pred

array(['functional', 'functional', 'functional', ..., 'functional',
       'functional', 'functional'], dtype=object)

In [37]:
y_pred = pd.DataFrame(y_pred)
y_pred.head()

            0
0  functional
1  functional
2  functional
3  functional
4  functional

In [38]:
y_pred.columns = ['status_group']
y_pred.head()

  status_group
0   functional
1   functional
2   functional
3   functional
4   functional